monitor.alsa.rules = [
  # --- DAC+ (I2S) ---
  {
    matches = [
      { node.name = "~alsa_output\\.platform-soc_107c000000_sound\\..*" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        node.pause-on-idle = false
        node.always-process = true

        audio.rate = 48000
        audio.format = "S32LE"

        api.alsa.period-size = 480
        api.alsa.period-num  = 3
        api.alsa.headroom    = 0
        api.alsa.start-delay = 0
      }
    }
  }

  # --- XVF3800 (USB) OUTPUT + INPUT ---
  {
    matches = [
      { node.name = "~alsa_(output|input)\\.usb-Seeed_Studio_reSpeaker.*" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        node.pause-on-idle = false
        node.always-process = true

        audio.rate = 16000
        audio.format = "S16LE"

        api.alsa.period-size = 480
        api.alsa.period-num  = 3
        api.alsa.headroom    = 128
        api.alsa.start-delay = 480
      }
    }
  }
]
