monitor.alsa.rules = [
  # --- XVF3800 OUTPUT + INPUT: always active ---
  {
    matches = [
      { node.name = "~alsa_(output|input)\\.usb-Seeed_Studio_reSpeaker.*" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        node.pause-on-idle = false
        node.always-process = true

        api.alsa.period-size = 240
        api.alsa.period-num  = 4
        api.alsa.headroom    = 128
        api.alsa.start-delay = 0
      }
    }
  }
]
