# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "aispeaker"
BBFILE_PATTERN_aispeaker = "^${LAYERDIR}/"
BBFILE_PRIORITY_aispeaker = "10"

LAYERDEPENDS_aispeaker = " \
    core \
    openembedded-layer \
    meta-python \
    networking-layer \
    multimedia-layer \
    filesystems-layer \
    raspberrypi \
"

LAYERSERIES_COMPAT_aispeaker = "wrynose"
