context.modules = [
  { name = libpipewire-module-combine-stream
    args = {
      combine.mode = sink
      node.name = "global_audio_sink"
      node.description = "System Audio AEC Master"
      combine.latency-compensate = false
      combine.props = {
        audio.position = [ FL FR ]
        node.force-rate = 48000
        node.force-quantum = 480
        node.group = "aec_group"
        node.always-process = true
        node.pause-on-idle = false
      }
      stream.props = {
        stream.dont-remix = true
      }
      stream.rules = [
        { matches = [ { node.name = "alsa_output.platform-soc_107c000000_sound.stereo-fallback" } ]
          actions = { create-stream = {
            audio.position = [ FL FR ]
            node.name = "stream_to_dac"
            node.autoconnect = true
            node.group = "aec_group"
            priority.driver = 1000
            audio.format = "S32LE"
            node.latency = "480/48000"
          } }
        }
        { matches = [ { node.name = "alsa_output.usb-Seeed_Studio_reSpeaker_XVF3800_4-Mic_Array_114993701254100081-00.analog-stereo" } ]
          actions = { create-stream = {
            audio.position = [ FL FR ]
            audio.rate = 16000
            node.name = "stream_to_respeaker"
            node.autoconnect = true
            node.group = "aec_group"
            priority.driver = 1
            resample.quality = 0
            audio.format = "S16LE"
          } }
        }
      ]
    }
  }
]
